### ISSUE TITLE
後台新增功能

### ISSUE THREAD

**Issue by ausir0726** [finpo/svg-cms#1]
- [x] 新增樣版 - 可以只上傳一張圖片，自動產生 svg 結構，並且嵌入這張圖片。
- [x] 在訂單list頁面，可以多選訂單後，直接開啟多張訂單的編輯頁面
- [x] 增加一個 note textarea 在訂單檢視頁面，以及在 list grid 也要顯示這個欄位
- [x] 新增兩個 order status [ pending , confirmed ] 不對應功能
- [x] 在訂單list頁面，可以多選訂單後，更改訂單的狀態

這個禮拜需要，謝謝。

**Comment by ausir0726** [comment]
補充：教學影片管理，要有一個產品類型的查詢欄位

原本的教學影片連結釋放再全站變數
客戶的教學影片依照不同的產品型態要製作不同的教學影片
需要將教學影片連結獨立出來做API

**Comment by joanne3634** [comment]
// 除了自動產生svg的那個以外其他都好了 
1.新增教學影片連結+shop_id 功能 
model / API.php < fn : get_om_info_by_hash  getOrder > 
model / Store.php  
js / model / StoreModel.js 
js / view / StorePanel.js 
database system_variable delete < Tutorial Video URL >
                store_list add < sl_tutorial_url >
2. 在訂單list頁面，可以多選訂單後，直接開啟多張訂單的編輯頁面
OrderMainPanel.js  Client Edit Pages onMenuitemClick3 
3. 增加一個 note textarea 在訂單檢視頁面，以及在 list grid 也要顯示這個欄位
js / view / OrderSubWindow.js
js / view / OrderSubAddWindow.js
js / view / OrderMainPanel.js  
js / model / OrderMainModel.js
database order_main add <  om_notes_2 > 
4. 新增兩個 order status [ pending , confirmed ] 不對應功能
 OrderMainPanel.js  < delete email coloum,  179~189 , 288~292 >
OrderSubWindow.js < 299 ~ 306 >
5. 在訂單list頁面，可以多選訂單後，更改訂單的狀態
 js / view / OrderMainPanel.js < fn : onDeliveryClick1 ~ 6 >
model / OrderMain.php  < fn : edit_om_status >

**Comment by joanne3634** [comment]
自動產生svg做完了 
js / view / svgMainOrderEditWindow.js
js / view / svgMainOrderAddWindow.js
model / Tool.php

**Comment by ausir0726** [comment]
自動產生 svg 我找不到觸發按鈕

**Comment by joanne3634** [comment]
不管是修改或是增加訂單 在加入新模板中 svg那個欄位 原本只能上傳svg 現在如果上傳非svg 會自動轉成svg 因此上傳一張圖片 上傳 模板即會新增

從我的 iPhone 傳送

羅 常瑋 <notifications@github.com<mailto:notifications@github.com>> 於 2015年3月23日 上午10:49 寫道：


自動產生 svg 我找不到觸發按鈕

**Comment by ausir0726** [comment]
checked
