### ISSUE TITLE
追加功能

### ISSUE THREAD

**Issue by ausir0726** [finpo/svg-cms#2]
- [x] Statistic 功能，增加匯出 excel 功能，欄位包含 Sku , Artist , Qty
- [x] 訂單 Status 上次追加的兩個，其中 Confirmed 要與 print order 相同，下載後該更改為 done
- [x] 訂單 Status 增加 "SLH" 跟 "DP Ready" ，功能與 customizing 相同，確認訂單後更改為 print orders

以上功能，謝謝。

**Comment by joanne3634** [comment]
這三個都好了 下面是改到的檔案 
OrderSubQueryPanel.js 
OrderMainPanel.js 
Administrator / SvgMain.php
Administrator / OrderMain.php 
Administrator / API.php

**Comment by ausir0726** [comment]
thanks for all .
